
ingredient_remap = {
"bread flour":"flour",
"wheat flour":"flour",
"pastry flour":"flour",
"cake flour": "flour",
"lemon peel":"lemon zest",
"lemon rind":"lemon zest",
"orange rind":"orange zest",
"orange peel":"orange zest",
"active dry yeast": "yeast",
"key lime juice": "lime juice",
"sugar":"white sugar",
"vanilla extract":"vanilla",
"butter flavored shortening": "shortening",
"vanilla wafer crumb": "vanilla wafer",
"heavy whipping cream":"whipping cream",
"half-and-half": "half-and-half cream",
"distilled white vinegar":"vinegar",
"extra virgin olive oil":"olive oil",
"oat":"oats",
"orange liqueur": "orange liquer",
"creme de menthe liqueur": "creme de menthe liquer",
"elbow macaroni":"macaroni",
"raspberry preserve": "jam",
"apricot preserve": "jam",
"apricot jam": "jam",
"pineapple preserve": "jam",
"raspberry jam": "jam",
"strawberry jam": "jam",
"lemon marmalade": "jam",
"orange marmalade": "jam",
"instant powdered milk": "milk powder",
"powdered milk": "milk powder",
"apricot spreadable fruit": "jam",
"white corn syrup": "corn syrup",
"milk chocolate chip": "chocolate chip",
"chocolate chunk": "chocolate chip",
"rice cereal": "crispy rice cereal",
"white chocolate chip": "white chocolate",
"milk chocolate candy kiss": "chocolate chip",
"cauliflower floret": "cauliflower",
"tequila": "liquer", #Questionable, alcohol type might matter
"whiskey": "liquer",
"brandy": "liquer",
"bourbon": "liquer",
"rum": "liquer",
"sherry": "liquer",
"beef stew meat": "beef",
"clove garlic": "garlic",
"cloves garlic": "garlic",
"cinnamon stick": "cinnamon",
"yellow onion": "onion",
"white onion": "onion",
"ginger root": "ginger",
"halibut steak": "halibut",
"slamon steak": "salmon",
"graham cracker crumb": "graham cracker",
"vegetable broth": "vegetable stock",
"anise seed": "anise",
"coriander seed": "coriander",
"crabmeat": "crab meat",
"chicken stock": "chicken broth",
"beef stock": "beef broth",
"beef bouillon granule": "beef bouillon",
"baking potatoe": "potato",
"white rice": "rice",
"cocoa powder": "cocoa",
"pearl barley": "barley",
"yellow squash": "squash",
"sea scallop": "scallop",
"bay scallop": "scallop",
"pimento": "pimento pepper",
"jalapeno": "jalapeno pepper",
"cod fillet": "cod",
"portobello mushroom": "mushroom",
"dungeness crabmeat": "crab meat",
"dog": "hot dog", #assuming...
"butternut squash": "squash",
"lobster tail": "lobster",
"lobster meat": "lobster",
"tiger prawn": "prawn",
"pork sausage": "sausage",
"chorizo sausage": "sausage",
"italian sausage": "sausage",
"pepperoni sausage": "sausage",
"seasoned salt": "seasoning salt",
"baking potato": "potato",
"russet potatoe": "potato",
"vanilla cream": "vanilla ice cream",
"broccoli floret": "broccoli",
"(9 inch) pie shell": "pie shell",
"(9 inch) pie crust": "pie shell",
"recipe pastry for a 9 inch double crust pie": "pie shell",
"recipe pastry for a 9 inch single crust pie": "pie shell",
"(9 inch) deep dish pie crust": "pie shell",
"(9 inch) prepared graham cracker crust": "graham cracker crust",
"mint leave": "mint",
"(18.25 ounce) packages devils food cake mix": "cake mix", #questionable, how deal with different mixes?
"pecan halve":"pecan", # Workaround
"walnut halve":"walnut", # Workaround
"molass":"molasses", # Workaround
"dark molass": "molasses", #Workaround
"clove": "cloves", #Workaround
"bay leave": "bay leaf", #Workaround
"basil leave": "basil", #Workaround
"potatoe": "potato", #Workaround
"white potatoe": "potato", #Workaround
"sweet potatoe": "sweet potato", #Workaround
"tomatoe": "tomato", #Workaround
"cinnamon red hot candie": "cinnamon red hot candy", #Workaround
"strawberrie": "strawberry", #Workaround
"blueberrie": "blueberry", #Workaround
"raspberrie": "raspberry", #Workaround
"blackberrie": "blackberry", #Workaround
"cranberrie": "cranberry", #Workaround
"peache": "peach", #Workaround
"cherrie": "cherry", #Workaround
"maraschino cherrie": "maraschino cherry", #Workaround
"unsalted butter":"butter" # Questionable, salt content matters
}

adjectives = [
'-',
'any',
'and',
'active',
'boneless',
'boiling',
'blanched',
'brewed',
'buttery',
'bunch',
'canned',
'chopped',
'crunchy',
'crumbled',
'coarsely',
'cold',
'cooked',
'cooking',
'cubed',
'cube',
'crisp',
'crushed',
'creamy',
'cut',
'dark',
'dash',
'deveined',
'diced',
'dried', # debateable, this sometimes matters
'dry',
'drained',
'extra-lean',
'fat',
'fine',
'flake',
'fillet',
'fillets',
'free',
'ears',
'flaked',
'flavor',
'finely',
'frozen',
'fresh',
'freshly',
'grated',
'granule',
'green',
'ground',
'hard-cooked',
'head',
'hot',
'ice',
'instant',
'julienne',
'julienned',
'kosher',
'kernel',
'large',
'lean',
'light',
'low-fat',
'lowfat',
'long-grain',
'lukewarm',
'mashed',
'medium',
'melted',
'minced',
'mini',
'miniature',
'natural',
'nonfat',
'packed',
'peeled',
'pitted',
'plain',
'prepared',
'pureed',
'pints',
'(optional)', #do we want to include these ingredients?
'quick',
'quick-cooking',
'red',
'reduced',
'rendered',
'ripe',
'rolled',
'round',
'roasted',
'real',
'salted', #okay to remove?
'seedless',
'sharp',
'semi-sweet',
'semisweet',
'shucked',
'sifted',
'shredded',
'sliced',
'slivered',
'slices',
'sprigs',
'sour',
'sprig',
'split',
'spicy',
'shelled',
'small',
'smoked',
'smooth',
'stewed',
'sweet',
'super',
'stalk',
'stalks',
'tart',
'taste',
'thinly',
'twist',
'to',
'to taste',
'toasted',
'unbaked',
'uncooked',
'unflavored',
'unwrapped',
'unsweetened',
'unbleached',
'unsulfured',
'wax',
'warm',
'wild',
'whole'
]

