
ingredient_remap = {
"bread flour":"flour",
"wheat flour":"flour",
"lemon peel":"lemon zest",
"lemon rind":"lemon zest",
"orange rind":"orange zest",
"orange peel":"orange zest",
"active dry yeast": "yeast",
"sugar":"white sugar",
"vanilla extract":"vanilla",
"heavy whipping cream":"whipping cream",
"distilled white vinegar":"vinegar",
"extra virgin olive oil":"olive oil",
"rolled oat":"oats",
"rolled oats": "oats",
"quick cooking oats": "oats",
"raspberry jam": "jam",
"instant powdered milk": "milk powder",
"apricot spreadable fruit": "jam",
"white corn syrup": "corn syrup",
"semisweet chocolate chips": "chocolate chip",
"milk chocolate candy kisses, unwrapped": "milk chocolate",
"pecan halv":"pecan", # Workaround
"egg whit":"egg white", # Workaround
"molass":"molasses", # Workaround
"unsalted butter":"butter" # Questionable, salt content matters
}

adjectives = [
'boneless',
'boiling',
'chopped',
'cold',
'cooked',
'cubed',
'crushed',
'creamy',
'diced',
'dried',
'dry',
'flaked',
'frozen',
'grated',
'green',
'ground',
'hot',
'large',
'low-fat',
'lukewarm',
'mashed',
'minced',
'packed',
'peeled',
'red',
'real',
'semi-sweet',
'sifted',
'shredded',
'sliced',
'unbaked',
'unwrapped',
'warm'
]

